POST http://localhost:8080/videos
Content-Type: application/json

{
  "title": "Video 01",
  "description": "Descrição do video 1",
  "duration": 180
}

###

GET http://localhost:8080/videos?search=node

###

PUT http://localhost:8080/videos/f93e784d-69df-45a2-ad19-ddf867577459
Content-Type: application/json

{
  "title": "Video node",
  "description": "Descrição do video node",
  "duration": 180
}

###

DELETE http://localhost:8080/videos/f93e784d-69df-45a2-ad19-ddf867577459